# Generated by Django 2.2.6 on 2019-10-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_user_image.jpg', upload_to='profile_pics'),
        ),
    ]
