# Generated by Django 2.2.6 on 2019-10-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-record_date',)},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-record_date',)},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=20),
        ),
    ]
